# Compose file is designed to run this on a local machine for development.
version: "3"
services:
  wordpress-starter-react-plugin:
    container_name: wordpress-starter-react-plugin
    image: maddog986/php-nginx-mysql-server:latest
    volumes:
      - ./wordpress_plugin:/var/www/wp-content/plugins/wordpress_plugin/
    ports:
      - 8084:80 # web port
    environment:
      - WEBSITE_HOSTNAME=localhost:3000 # wordpress goes through webpack dev server
      - WORDPRESS_INSTALL=true
      - WORDPRESS_TITLE=WordPress
      - WORDPRESS_ADMIN_EMAIL=noemail@domain.com
      - WORDPRESS_INSTALL_PLUGIN=wordpress_plugin
    restart: unless-stopped
    networks:
      wsp_network:
        ipv4_address: 172.34.30.99

networks:
  wsp_network:
    ipam:
      driver: default
      config:
        - subnet: 172.34.30.0/16
